name: Deploy to Vercel

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel dev webhook
        if: github.ref == 'refs/heads/dev'
        run: curl -X POST ${{ secrets.VERCEL_DEV_WEBHOOK }}

      - name: Trigger Vercel main webhook
        if: github.ref == 'refs/heads/main'
        run: curl -X POST ${{ secrets.VERCEL_MAIN_WEBHOOK }}
